# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.csci373.Ranksaildex.Ranksaildex
load: startup
name: ${project.name}
version: ${project.version}
author: SampleAuthor
description: ${project.description}
commands:
  siege:
    description: all commands start with siege
    usage: siege /<command> arguments
    permission: siege.*
permissions:
  siege.*:
    description: gives all permissions of the siege plugin
    default: true
    children:
      siege.message:
        description: gives permission to set the siege message using the siege command
      siege.on:
        description: activates the zombie siege
      siege.off:
        description: deactivates the zombie siege